---
server:
  address: "127.0.0.1"
  port: 8080

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 0
    webhook_secret: "your_webhook_secret"
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----